package api

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os/exec"
	"testing"
)

// seedE2EAdmin creates admin@<slug>.com via SQL like the manual bootstrap:
// user + tenant_admin user_role. The password is set with a real bcrypt hash
// generated by a throwaway Go program (bcrypt cost 12). If the user exists but
// is inactive (deactivated by a previous mapping-test run), it is reactivated.
func seedE2EAdmin(t *testing.T, slug string) {
	t.Helper()

	tenantID := tenantIDBySlug(t, slug)
	email := "admin@" + slug + ".com"
	if userExists(t, tenantID, email) {
		psql(t, fmt.Sprintf("UPDATE users SET status = 'active' WHERE tenant_id = '%s' AND email = '%s'", tenantID, email))
		// Re-grant the admin role (idempotent) in case user_roles changed.
		psql(t, fmt.Sprintf(
			`INSERT INTO user_roles (id, tenant_id, user_id, role_id, created_at, updated_at)
			 SELECT gen_random_uuid(), '%s', u.id, r.id, now(), now() FROM users u JOIN roles r ON r.tenant_id = '%s' AND r.name = 'tenant_admin'
			 WHERE u.tenant_id = '%s' AND u.email = '%s'
			 ON CONFLICT DO NOTHING`, tenantID, tenantID, tenantID, email))
		return
	}

	hash := bcryptHash(t, "Secret123!")
	psql(t, fmt.Sprintf(
		"INSERT INTO users (id, tenant_id, email, password_hash, first_name, last_name, status, created_at, updated_at) VALUES (gen_random_uuid(), '%s', '%s', '%s', 'E2E', 'Admin', 'active', now(), now())",
		tenantID, email, hash))
	psql(t, fmt.Sprintf(
		`INSERT INTO user_roles (id, tenant_id, user_id, role_id, created_at, updated_at)
		 SELECT gen_random_uuid(), '%s', u.id, r.id, now(), now() FROM users u JOIN roles r ON r.tenant_id = '%s' AND r.name = 'tenant_admin'
		 WHERE u.tenant_id = '%s' AND u.email = '%s'`, tenantID, tenantID, tenantID, email))
}

func tenantIDBySlug(t *testing.T, slug string) string {
	t.Helper()
	out := psql(t, fmt.Sprintf("SELECT id FROM tenants WHERE slug = '%s'", slug))
	return out
}

func userExists(t *testing.T, tenantID, email string) bool {
	t.Helper()
	out := psql(t, fmt.Sprintf("SELECT id FROM users WHERE tenant_id = '%s' AND email = '%s'", tenantID, email))
	return out != ""
}

func bcryptHash(t *testing.T, password string) string {
	t.Helper()
	return bcryptViaHelper(t, password)
}

func bcryptViaHelper(t *testing.T, password string) string {
	t.Helper()
	dir := t.TempDir()
	main := `package main

import (
	"fmt"
	"os"

	"golang.org/x/crypto/bcrypt"
)

func main() {
	h, err := bcrypt.GenerateFromPassword([]byte(os.Args[1]), 12)
	if err != nil {
		panic(err)
	}
	fmt.Print(string(h))
}
`
	writeFile(t, dir+"/main.go", main)
	writeFile(t, dir+"/go.mod", "module bcryptgen\n\ngo 1.25.0\n\nrequire golang.org/x/crypto v0.53.0\n")
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = dir
	var errBuf bytes.Buffer
	cmd.Stderr = &errBuf
	if err := cmd.Run(); err != nil {
		t.Fatalf("go mod tidy: %v (%s)", err, errBuf.String())
	}
	cmd = exec.Command("go", "run", ".", password)
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("bcrypt gen: %v", err)
	}
	return string(out)
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := osWriteFile(path, content); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func randomSuffix() string {
	b := make([]byte, 3)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}
